### ISSUE TITLE
CI command is hanging

### ISSUE THREAD

**Issue by clemenshelm** [mrship/middleman-jasmine#12]
I cannot get the `rake middleman_jasmine:ci` command to work. There is no error, it's just hanging.

I debugged the issue and found out that the problem occurs in https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/runners/phantom_jasmine_run.js:17 where PhatomJS expects to be called from Jasmine. This should be done in https://github.com/jasmine/jasmine-gem/blob/master/lib/jasmine/runners/phantom_boot.js:6.

However, this phantom_boot.js file doesn't seem to be loaded. Is there a configuration setting where I can tell Jasmine to load this file?

**Comment by matstc** [comment]
I had the same error and the PR fixed it for me.

**Comment by clemenshelm** [comment]
My pleasure :)

**Comment by mrship** [comment]
Closed with #13
